export {
  SCROLL_UP_BTN,
  CATS_DATA,
  TEMPLATE,
  CATS_LIST,
  SHOW_MORE_BUTTON,
  ERROR_MESAGE, FORM, SUBSCRIBE_BUTTON
};

const TEMPLATE = document.querySelector('.template').content;
const CATS_LIST = document.querySelector('.card-items');
const SHOW_MORE_BUTTON = document.querySelector('.button_show-more');
const SCROLL_UP_BTN = document.querySelector('.scroll-up');
const SUBSCRIBE_BUTTON = document.querySelector('.button_footer');

const ERROR_MESAGE = {
  errorEmpty: 'Это обязательное поле',
  error: 'необходим e-mail в формате: email@gmail.com',
};

const FORM = document.querySelector('.footer__email-form');
// ======= котики
const CATS_DATA = [
  {
    discount: '-40%',
    title: 'Кот полосатый ',
    color: 'Серый',
    age: '2',
    price: '9000',
    pawCount: '4',
    count: '3',
    img: 'https://i.ibb.co/qsMmJkx/Cat-1.png',
  },
  {
    discount: '',
    title: 'Кот полосатый ',
    color: 'Черный',
    age: '3',
    price: '20000',
    pawCount: '4',
    count: 0,
    img: 'https://i.ibb.co/t3ZXTDH/cat-3.png',
  },
  {
    discount: '-10%',
    title: 'Кот полосатый ',
    color: 'Рыжий',
    age: '2',
    price: '50000',
    pawCount: '4',
    count: '2',
    img: 'https://i.ibb.co/J7ZcCRk/cat-2.png',
  },
  {
    discount: '',
    title: 'Кот полосатый ',
    color: 'Коричневый',
    age: '2',
    price: '24000',
    pawCount: '4',
    count: '3',
    img: 'https://i.ibb.co/qsMmJkx/Cat-1.png',
  },
  {
    discount: '-40%',
    title: 'Кот полосатый ',
    color: 'Коричневый',
    age: '7',
    price: '30000',
    pawCount: '4',
    count: '4',
    img: 'https://i.ibb.co/t3ZXTDH/cat-3.png',
  },
  {
    discount: '-40%',
    title: 'Кот полосатый ',
    color: 'Белый',
    age: '8',
    price: '30000',
    pawCount: '4',
    count: '0',
    img: 'https://i.ibb.co/J7ZcCRk/cat-2.png',
  },
  {
    discount: '',
    title: 'Кот полосатый ',
    color: 'Коричневый',
    age: '2',
    price: '30000',
    pawCount: '4',
    count: '10',
    img: 'https://i.ibb.co/t3ZXTDH/cat-3.png',
  },
  {
    discount: '-40%',
    title: 'Кот полосатый ',
    color: 'Коричневый',
    age: '1',
    price: '10000',
    pawCount: '4',
    count: '3',
    img: 'https://i.ibb.co/qsMmJkx/Cat-1.png',
  },
  {
    discount: '',
    title: 'Кот полосатый ',
    color: 'Коричневый',
    age: '3',
    price: '30000',
    pawCount: '4',
    count: '2',
    img: 'https://i.ibb.co/t3ZXTDH/cat-3.png',
  },
  {
    discount: '',
    title: 'Кот полосатый ',
    color: 'Коричневый',
    age: '6',
    price: '15000',
    pawCount: '4',
    count: '2',
    img: 'https://i.ibb.co/J7ZcCRk/cat-2.png',
  },
  {
    discount: '-10%',
    title: 'Кот полосатый ',
    color: 'Коричневый',
    age: '2',
    price: '31000',
    pawCount: '4',
    count: '2',
    img: 'https://i.ibb.co/t3ZXTDH/cat-3.png',
  },
  {
    discount: '',
    title: 'Кот полосатый ',
    color: 'Коричневый',
    age: '3',
    price: ' 15000',
    pawCount: '4',
    count: '2',
    img: 'https://i.ibb.co/qsMmJkx/Cat-1.png',
  },
  {
    discount: '',
    title: 'Кот полосатый ',
    color: 'Коричневый',
    age: '5',
    price: '30000',
    pawCount: '4',
    count: '2',
    img: 'https://i.ibb.co/J7ZcCRk/cat-2.png',
  },
  {
    discount: '-40%',
    title: 'Кот полосатый ',
    color: 'Коричневый',
    age: '2',
    price: '30000',
    pawCount: '4',
    count: '2',
    img: 'https://i.ibb.co/t3ZXTDH/cat-3.png',
  },
  {
    discount: '-40%',
    title: 'Кот полосатый ',
    color: 'Коричневый',
    age: '2',
    price: '10000',
    pawCount: '4',
    count: '2',
    img: 'https://i.ibb.co/J7ZcCRk/cat-2.png',
  },
  {
    discount: '',
    title: 'Кот полосатый ',
    color: 'Красный',
    age: '2',
    price: '20000',
    pawCount: '4',
    count: '2',
    img: 'https://i.ibb.co/qsMmJkx/Cat-1.png',
  },
  {
    discount: '',
    title: 'Кот полосатый ',
    color: 'Коричневый',
    age: '2',
    price: '30000',
    pawCount: '4',
    count: '4',
    img: 'https://i.ibb.co/t3ZXTDH/cat-3.png',
  },
];
